# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri Feb 18 10:11:19 2022
# ------------------------------------------------

package:
  name: setuptools
  version: 60.9.3
source:
  patches:
    - patches/0010-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch
    - patches/0012-Disable-new-dtags-in-unixccompiler.py.patch
    - patches/0021-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
  sha256: 2347b2b432c891a863acadca2da9ac101eae6169b1d3dfee2ec605ecd50dbfe5
  url: https://pypi.io/packages/source/s/setuptools/setuptools-60.9.3.tar.gz
build:
  number: '0'
  string: py39h2804cbe_0
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2021.10.8 h033912b_0
    - cctools_osx-64 973.0.1 h609b070_7
    - cctools_osx-arm64 973.0.1 hd1d4517_7
    - clang 12.0.1 h694c41f_4
    - clang-12 12.0.1 default_he082bbe_4
    - clang_osx-arm64 12.0.1 h160513a_6
    - clangxx 12.0.1 default_he082bbe_4
    - compiler-rt 12.0.1 he01351e_0
    - compiler-rt_osx-64 12.0.1 hd3f61c9_0
    - cross-python_osx-arm64 3.9 21_cpython
    - crossenv 1.2.0 pyhd8ed1ab_0
    - gettext 0.19.8.1 hd1a6beb_1008
    - ld64_osx-64 609 hc6b1d1e_7
    - ld64_osx-arm64 609 hf6d2360_7
    - libclang-cpp12 12.0.1 default_he082bbe_4
    - libcxx 12.0.1 habf9029_1
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.16 haf1e3a3_0
    - libllvm11 11.1.0 hd011deb_3
    - libllvm12 12.0.1 hd011deb_2
    - libzlib 1.2.11 h9173be1_1013
    - llvm-tools 12.0.1 hd011deb_2
    - lz4-c 1.9.3 he49afe7_1
    - ncurses 6.3 he49afe7_0
    - openssl 3.0.0 h0d85af4_2
    - popt 1.16 h7b079dc_2002
    - python 3.9.10 hea1dfa3_2_cpython
    - readline 8.1 h05e3726_0
    - rsync 3.2.3 h652f650_3
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - sqlite 3.37.0 h23a322b_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.12 h5dbffcc_0
    - tzdata 2021e he74cb21_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.5 haf1e3a3_1
    - zlib 1.2.11 h9173be1_1013
    - zstd 1.5.2 h582d3a0_0
  host:
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2021.10.8 h4653dfc_0
    - libffi 3.4.2 h3422bc3_5
    - libzlib 1.2.11 hee7b306_1013
    - ncurses 6.3 hc470f4d_0
    - openssl 3.0.0 h3422bc3_2
    - python 3.9.10 h38ef502_2_cpython
    - readline 8.1 hedafd6a_0
    - sqlite 3.37.0 h72a2b83_0
    - tk 8.6.12 he1e0b03_0
    - tzdata 2021e he74cb21_0
    - xz 5.2.5 h642e427_1
    - zlib 1.2.11 hee7b306_1013
  run:
    - python >=3.9,<3.10.0a0
    - python >=3.9,<3.10.0a0 *_cpython
    - python_abi 3.9.* *_cp39
test:
  imports:
    - pkg_resources
    - setuptools
about:
  description: 'Setuptools is a fully-featured, actively-maintained, and stable library

    designed to facilitate packaging Python projects.

    '
  dev_url: https://github.com/pypa/setuptools
  doc_source_url: https://github.com/pypa/setuptools/tree/master/docs
  doc_url: http://pythonhosted.org/setuptools/
  home: https://github.com/pypa/setuptools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Download, build, install, upgrade, and uninstall Python packages
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - isuruf
    - jakirkham
    - msarahan
    - nicoddemus
    - ocefpaf
    - rgommers
