# This file created by conda-build 3.21.4
# ------------------------------------------------

package:
  name: zlib
  version: 1.2.11
source:
  sha256: c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1
  url: http://zlib.net/zlib-1.2.11.tar.gz
build:
  number: 1013
  run_exports:
    - libzlib >=1.2.11,<1.3.0a0
  string: hee7b306_1013
requirements:
  build:
    - clang_bootstrap_osx-arm64 11.0.0.rc1 hd819f65_12
  host:
    - libzlib 1.2.11 hee7b306_1013
  run:
    - libzlib 1.2.11 hee7b306_1013
test:
  commands:
    - test -f ${PREFIX}/lib/libz.a
    - test -f ${PREFIX}/lib/libz${SHLIB_EXT}
    - test -f ${PREFIX}/include/zlib.h
about:
  description: 'zlib is designed to be a free, general-purpose, lossless data-compression

    library for use on virtually any computer hardware and operating system.

    '
  dev_url: https://github.com/madler/zlib
  doc_url: http://zlib.net/manual.html
  home: http://zlib.net/
  license: Zlib
  license_family: Other
  license_file: license.txt
  summary: Massively spiffy yet delicately unobtrusive compression library
extra:
  copy_test_source_files: true
  feedstock-name: zlib
  final: true
  recipe-maintainers:
    - groutr
    - isuruf
    - msarahan
    - ocefpaf
