# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri Oct  8 22:44:23 2021
# ------------------------------------------------

package:
  name: ca-certificates
  version: 2021.10.8
source:
  sha256: 78884e7c1d4b00ce3cea67b44566851c4343c120abd683433ce934a68ea58872
  url: https://pypi.io/packages/source/c/certifi/certifi-2021.10.8.tar.gz
build:
  number: '0'
  string: h4653dfc_0
requirements:
  build: []
  run: []
test:
  commands:
    - test -f "${PREFIX}/ssl/cacert.pem"
    - test -f "${PREFIX}/ssl/cert.pem"
    - curl --cacert "${PREFIX}/ssl/cacert.pem" https://www.google.com
  requires:
    - curl
about:
  home: https://github.com/conda-forge/ca-certificates-feedstock
  license: ISC
  license_file: LICENSE
  summary: Certificates for use with other packages.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
