# This file created by conda-build 3.21.6
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Tue Nov 23 10:56:49 2021
# ------------------------------------------------

package:
  name: conda
  version: 4.11.0
source:
  fn: conda-4.11.0.tar.gz
  patches:
    - gh9946_utf_16_replacement.patch
  sha256: 1843355ccb93afb05f2a307e1fc37403fb9976da799236eebc3adee1c716c5fc
  url: https://github.com/conda/conda/archive/4.11.0.tar.gz
build:
  always_include_files:
    - bin/activate
    - bin/conda
    - bin/deactivate
  number: '0'
  string: py39h2804cbe_0
requirements:
  build:
    - ca-certificates 2021.10.8 h033912b_0
    - cctools_osx-64 973.0.1 h3e07e27_2
    - cctools_osx-arm64 949.0.1 h55de48a_23
    - clang 12.0.1 h694c41f_4
    - clang-12 12.0.1 default_he082bbe_4
    - clang_osx-arm64 12.0.1 h40be2b1_2
    - clangxx 12.0.1 default_he082bbe_4
    - compiler-rt 12.0.1 he01351e_0
    - compiler-rt_osx-64 12.0.1 hd3f61c9_0
    - cross-python_osx-arm64 3.9 20_cpython
    - crossenv 1.0 pyhd8ed1ab_6
    - gettext 0.19.8.1 hd1a6beb_1008
    - ld64_osx-64 609 h2487922_2
    - ld64_osx-arm64 530 h3681fde_23
    - ldid 2.1.2 h6a69015_3
    - libclang-cpp12 12.0.1 default_he082bbe_4
    - libcxx 12.0.1 habf9029_0
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.16 haf1e3a3_0
    - libllvm12 12.0.1 hd011deb_2
    - libzlib 1.2.11 h9173be1_1013
    - llvm-tools 12.0.1 hd011deb_2
    - lz4-c 1.9.3 he49afe7_1
    - ncurses 6.2 h2e338ed_4
    - openssl 3.0.0 h0d85af4_2
    - popt 1.16 h7b079dc_2002
    - python 3.9.7 h38b4d05_3_cpython
    - readline 8.1 h05e3726_0
    - rsync 3.2.3 h652f650_3
    - sed 4.7 h3efe00b_1000
    - sqlite 3.36.0 h23a322b_2
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.11 h5dbffcc_1
    - tzdata 2021e he74cb21_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.5 haf1e3a3_1
    - zlib 1.2.11 h9173be1_1013
    - zstd 1.5.0 h582d3a0_0
  host:
    - ca-certificates 2021.10.8 h4653dfc_0
    - colorama 0.4.4 pyh9f0ad1d_0
    - conda-package-handling 1.7.3 py39h5161555_1
    - libzlib 1.2.11 hee7b306_1013
    - ncurses 6.2 h9aa5885_4
    - openssl 3.0.0 h3422bc3_2
    - pip 21.3.1 pyhd8ed1ab_0
    - python 3.9.7 hc0da0df_3_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 hedafd6a_0
    - ruamel_yaml 0.15.80 py39h5161555_1006
    - setuptools 59.2.0 py39h2804cbe_0
    - six 1.16.0 pyh6c4a22f_0
    - sqlite 3.36.0 h72a2b83_2
    - tk 8.6.11 he1e0b03_1
    - tqdm 4.62.3 pyhd8ed1ab_0
    - tzdata 2021e he74cb21_0
    - wheel 0.37.0 pyhd8ed1ab_1
    - xz 5.2.5 h642e427_1
    - yaml 0.2.5 h642e427_0
    - zlib 1.2.11 hee7b306_1013
  run:
    - conda-package-handling >=1.3.0
    - pycosat >=0.6.3
    - pyopenssl >=16.2.0
    - python >=3.9,<3.10.0a0
    - python >=3.9,<3.10.0a0 *_cpython
    - python_abi 3.9.* *_cp39
    - requests >=2.18.4,<3
    - ruamel_yaml >=0.11.14,<0.16
    - setuptools >=31.0.1
  run_constrained:
    - conda-build >=3
    - conda-content-trust >=0.1.1
    - conda-env >=2.6
    - cytoolz >=0.8.1
test:
  commands:
    - unset CONDA_SHLVL
    - eval "$(python -m conda shell.bash hook)"
    - conda activate base
    - export PYTHON_MAJOR_VERSION=$(python -c "import sys; print(sys.version_info[0])")
    - export TEST_PLATFORM=$(python -c "import sys; print('win' if sys.platform.startswith('win')
      else 'unix')")
    - export PYTHONHASHSEED=$(python -c "import random as r; print(r.randint(0,4294967296))")
      && echo "PYTHONHASHSEED=$PYTHONHASHSEED"
    - env | sort
    - conda info
    - conda create -y -p ./built-conda-test-env
    - conda activate ./built-conda-test-env
    - echo $CONDA_PREFIX
    - '[ "$CONDA_PREFIX" = "$PWD/built-conda-test-env" ] || exit 1'
    - conda deactivate
  downstreams:
    - conda-smithy
  files:
    - test_conda.sh
  imports:
    - conda
    - conda_env
  requires:
    - mock
    - pexpect
    - pytest
    - responses
  source_files:
    - setup.cfg
    - tests
about:
  description: 'Conda is an open source package management system and environment
    management system for installing multiple versions of software packages and their
    dependencies and switching easily between them. It works on Linux, OS X and Windows,
    and was created for Python programs but can package and distribute any software.

    '
  dev_url: https://github.com/conda/conda
  doc_url: https://conda.io/projects/conda/en/latest/
  home: https://conda.io
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: OS-agnostic, system-level binary package and environment manager.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - isuruf
    - jakirkham
    - jezdez
    - kalefranz
    - mbargull
    - mcg1969
    - mingwandroid
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
