# This file created by conda-build 3.21.4
# ------------------------------------------------

package:
  name: openssl
  version: 1.1.1l
source:
  patches:
    - patches/0001-Don-t-use-USE_BCRYPTGENRANDOM-for-VS-older-than-2015.patch
    - patches/0002-Darwin-platform-allows-to-build-on-releases-before-Y.patch
  sha256: 0b7a3e5e59c34827fe0c3a74b7ec8baef302b98fa80088d7f9153aa16fa76bd1
  url: http://www.openssl.org/source/openssl-1.1.1l.tar.gz
build:
  ignore_run_exports_from:
    - perl *
  no_link: lib/libcrypto.1.1.dylib
  number: 0
  run_exports:
    - openssl >=1.1.1l,<1.1.2a
  string: h3422bc3_0
requirements:
  build:
    - cctools_osx-64 949.0.1 h6407bdd_22
    - cctools_osx-arm64 949.0.1 h55de48a_22
    - clang 11.1.0 h694c41f_1
    - clang-11 11.1.0 default_he082bbe_1
    - clang_osx-arm64 11.1.0 h40be2b1_3
    - clangxx 11.1.0 default_he082bbe_1
    - compiler-rt 11.1.0 h654b07c_0
    - compiler-rt_osx-64 11.1.0 h8c5fa43_0
    - ld64_osx-64 530 he8994da_21
    - ld64_osx-arm64 530 h3681fde_21
    - ldid 2.1.2 h7660a38_2
    - libclang-cpp11.1 11.1.0 default_he082bbe_1
    - libcxx 12.0.1 habf9029_0
    - libllvm11 11.1.0 hd011deb_2
    - libllvm12 12.0.1 hd011deb_2
    - llvm-tools 11.1.0 hd011deb_2
    - make 4.3 h22f3db7_1
    - perl 5.32.1 0_h0d85af4_perl5
    - tapi 1100.0.11 h9ce4665_0
    - zlib 1.2.11 h7795811_1010
  run:
    - ca-certificates
test:
  commands:
    - touch checksum.txt
    - openssl sha256 checksum.txt
about:
  dev_url: https://github.com/openssl/openssl
  doc_url: https://www.openssl.org/docs/man1.1.1/
  home: http://www.openssl.org/
  license: OpenSSL
  license_family: Apache
  license_file: LICENSE
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - carlodri
    - jakirkham
    - msarahan
    - ocefpaf
    - pelson
