# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Thu Nov  4 10:27:25 2021
# ------------------------------------------------

package:
  name: conda-package-handling
  version: 1.7.3
source:
  sha256: 6c01527200c9d9de18e64d2006cc97f9813707a34f3cb55bca2852ff4b06fb8d
  url: https://github.com/conda/conda-package-handling/archive/1.7.3.tar.gz
build:
  entry_points:
    - cph = conda_package_handling.cli:main
  missing_dso_whitelist: null
  number: '1'
  script: /Users/runner/miniforge3/conda-bld/conda-package-handling_1636022092101/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . --no-deps -vv
  string: py39h5161555_1
requirements:
  build:
    - ca-certificates 2021.10.8 h033912b_0
    - cctools_osx-64 949.0.1 h6407bdd_23
    - cctools_osx-arm64 949.0.1 h55de48a_23
    - clang 11.1.0 h694c41f_1
    - clang-11 11.1.0 default_he082bbe_1
    - clang_osx-arm64 11.1.0 h40be2b1_4
    - clangxx 11.1.0 default_he082bbe_1
    - compiler-rt 11.1.0 h654b07c_0
    - compiler-rt_osx-64 11.1.0 h8c5fa43_0
    - cross-python_osx-arm64 3.9 17_cpython
    - crossenv 1.0 pyhd8ed1ab_6
    - cython 0.29.24 py39h9fcab8e_1
    - gettext 0.19.8.1 hd1a6beb_1008
    - ld64_osx-64 530 he8994da_21
    - ld64_osx-arm64 530 h3681fde_21
    - ldid 2.1.2 h6a69015_3
    - libclang-cpp11.1 11.1.0 default_he082bbe_1
    - libcxx 12.0.1 habf9029_0
    - libffi 3.4.2 he49afe7_4
    - libiconv 1.16 haf1e3a3_0
    - libllvm11 11.1.0 hd011deb_2
    - libllvm12 12.0.1 hd011deb_2
    - libzlib 1.2.11 h9173be1_1013
    - llvm-tools 11.1.0 hd011deb_2
    - lz4-c 1.9.3 he49afe7_1
    - ncurses 6.2 h2e338ed_4
    - openssl 3.0.0 h0d85af4_2
    - popt 1.16 h7b079dc_2002
    - python 3.9.7 h38b4d05_3_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 h05e3726_0
    - rsync 3.2.3 h652f650_3
    - sed 4.7 h3efe00b_1000
    - sqlite 3.36.0 h23a322b_2
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.11 h5dbffcc_1
    - tzdata 2021e he74cb21_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.5 haf1e3a3_1
    - zlib 1.2.11 h9173be1_1013
    - zstd 1.5.0 h582d3a0_0
  host:
    - _libarchive_static_for_cph 3.3.3 h37bb66c_5
    - ca-certificates 2021.10.8 h4653dfc_0
    - cython 0.29.24 py39hfb83b0d_1
    - libcxx 12.0.1 h168391b_0
    - libzlib 1.2.11 hee7b306_1013
    - ncurses 6.2 h9aa5885_4
    - openssl 3.0.0 h3422bc3_2
    - pip 21.3.1 pyhd8ed1ab_0
    - python 3.9.7 hc0da0df_3_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 hedafd6a_0
    - setuptools 58.5.2 py39h2804cbe_0
    - sqlite 3.36.0 h72a2b83_2
    - tk 8.6.11 he1e0b03_1
    - tzdata 2021e he74cb21_0
    - wheel 0.37.0 pyhd8ed1ab_1
    - xz 5.2.5 h642e427_1
    - zlib 1.2.11 hee7b306_1013
  run:
    - python >=3.9,<3.10.0a0
    - python >=3.9,<3.10.0a0 *_cpython
    - python_abi 3.9.* *_cp39
    - six
    - tqdm
test:
  commands:
    - pytest tests -k "not test_secure_refusal_to_extract_abs_paths"
  imports:
    - conda_package_handling
    - conda_package_handling.archive_utils_cy
  requires:
    - mock
    - pytest
    - pytest-cov
    - pytest-mock
  source_files:
    - tests
about:
  home: https://github.com/conda/conda-package-handling
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - static_deps_licenses/bzip2.txt
    - static_deps_licenses/libarchive.txt
    - static_deps_licenses/libiconv.txt
    - static_deps_licenses/zlib.txt
    - static_deps_licenses/zstd.txt
  summary: Create and extract conda packages of various formats
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - beckermr
    - dbast
    - msarahan
