# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Tue Nov  2 14:12:37 2021
# ------------------------------------------------

package:
  name: pysocks
  version: 1.7.1
source:
  sha256: 3f8804571ebe159c380ac6de37643bb4685970655d3bba243530d6558b799aa0
  url: https://pypi.io/packages/source/P/PySocks/PySocks-1.7.1.tar.gz
build:
  number: '4'
  script: /Users/runner/miniforge3/conda-bld/pysocks_1635862736740/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps -vv
  string: py39h2804cbe_4
requirements:
  build:
    - ca-certificates 2021.10.8 h033912b_0
    - cctools_osx-64 973.0.1 h3e07e27_2
    - cctools_osx-arm64 949.0.1 h55de48a_23
    - clang 12.0.1 h694c41f_4
    - clang-12 12.0.1 default_he082bbe_4
    - clang_osx-arm64 12.0.1 h40be2b1_1
    - clangxx 12.0.1 default_he082bbe_4
    - compiler-rt 12.0.1 he01351e_0
    - compiler-rt_osx-64 12.0.1 hd3f61c9_0
    - cross-python_osx-arm64 3.9 17_cpython
    - crossenv 1.0 pyhd8ed1ab_6
    - gettext 0.19.8.1 hd1a6beb_1008
    - ld64_osx-64 609 h2487922_2
    - ld64_osx-arm64 530 h3681fde_23
    - ldid 2.1.2 h6a69015_3
    - libclang-cpp12 12.0.1 default_he082bbe_4
    - libcxx 12.0.1 habf9029_0
    - libffi 3.4.2 he49afe7_4
    - libiconv 1.16 haf1e3a3_0
    - libllvm12 12.0.1 hd011deb_2
    - libzlib 1.2.11 h9173be1_1013
    - llvm-tools 12.0.1 hd011deb_2
    - lz4-c 1.9.3 he49afe7_1
    - ncurses 6.2 h2e338ed_4
    - openssl 3.0.0 h0d85af4_1
    - popt 1.16 h7b079dc_2002
    - python 3.9.7 h38b4d05_3_cpython
    - readline 8.1 h05e3726_0
    - rsync 3.2.3 h652f650_3
    - sed 4.7 h3efe00b_1000
    - sqlite 3.36.0 h23a322b_2
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.11 h5dbffcc_1
    - tzdata 2021e he74cb21_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.5 haf1e3a3_1
    - zlib 1.2.11 h9173be1_1013
    - zstd 1.5.0 h582d3a0_0
  host:
    - ca-certificates 2021.10.8 h4653dfc_0
    - libzlib 1.2.11 hee7b306_1013
    - ncurses 6.2 h9aa5885_4
    - openssl 3.0.0 h3422bc3_1
    - pip 21.3.1 pyhd8ed1ab_0
    - python 3.9.7 hc0da0df_3_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 hedafd6a_0
    - setuptools 58.4.0 py39h2804cbe_1
    - sqlite 3.36.0 h72a2b83_2
    - tk 8.6.11 he1e0b03_1
    - tzdata 2021e he74cb21_0
    - wheel 0.37.0 pyhd8ed1ab_1
    - xz 5.2.5 h642e427_1
    - zlib 1.2.11 hee7b306_1013
  run:
    - python >=3.9,<3.10.0a0
    - python >=3.9,<3.10.0a0 *_cpython
    - python_abi 3.9.* *_cp39
test:
  imports:
    - socks
about:
  dev_url: https://github.com/Anorov/PySocks
  doc_url: https://github.com/Anorov/PySocks/blob/master/README.md
  home: https://github.com/Anorov/PySocks
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python SOCKS client module. See https://github.com/Anorov/PySocks for
    more information.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
