# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Sep 20 17:47:10 2021
# ------------------------------------------------

package:
  name: tqdm
  version: 4.62.3
source:
  sha256: d359de7217506c9851b7869f3708d8ee53ed70a1b8edbba4dbcb47442592920d
  url: https://pypi.io/packages/source/t/tqdm/tqdm-4.62.3.tar.gz
build:
  entry_points:
    - tqdm = tqdm.cli:main
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/tqdm_1632160078689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.5.30 ha878542_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.4.2 h9c3ff4c_1
    - libgcc-ng 11.2.0 h1d223b6_8
    - libgomp 11.2.0 h1d223b6_8
    - libstdcxx-ng 11.2.0 he4da1e4_8
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1l h7f98852_0
    - packaging 21.0 pyhd8ed1ab_0
    - pip 21.2.4 pyhd8ed1ab_0
    - pyparsing 2.4.7 pyh9f0ad1d_0
    - python 3.9.7 hb7a2778_1_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 h46c0cb4_0
    - setuptools 58.0.4 py39hf3d152e_0
    - setuptools-scm 6.3.2 pyhd8ed1ab_0
    - setuptools_scm 6.3.2 hd8ed1ab_0
    - sqlite 3.36.0 h9cd32fc_1
    - tk 8.6.11 h27826a3_1
    - toml 0.10.2 pyhd8ed1ab_0
    - tomli 1.2.1 pyhd8ed1ab_0
    - tzdata 2021a he74cb21_1
    - wheel 0.37.0 pyhd8ed1ab_1
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - colorama
    - python >=2.7
test:
  commands:
    - pip check
    - tqdm --help
    - tqdm -v
    - pytest -k "not tests_perf"
  imports:
    - tqdm
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pytest-timeout
  source_files:
    - pyproject.toml
    - setup.cfg
    - tests
about:
  dev_url: https://tqdm.github.io/docs/tqdm
  doc_source_url: https://github.com/tqdm/tqdm/blob/master/README.rst
  doc_url: https://github.com/tqdm/tqdm#tqdm
  home: https://pypi.python.org/pypi/tqdm
  license: MPL-2.0 or MIT
  license_family: MOZILLA
  license_file: LICENCE
  summary: A Fast, Extensible Progress Meter
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - casperdcl
    - pmlandwehr
