# This file created by conda-build 3.21.6
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Sun Nov 28 14:01:10 2021
# ------------------------------------------------

package:
  name: sqlite
  version: 3.37.0
source:
  patches: null
  sha256: 731a4651d4d4b36fc7d21db586b2de4dd00af31fd54fb5a9a4b7f492057479f7
  url: https://www.sqlite.org/2021/sqlite-autoconf-3370000.tar.gz
build:
  number: '0'
  run_exports:
    - sqlite >=3.37.0,<4.0a0
  string: h72a2b83_0
requirements:
  build:
    - cctools_osx-64 949.0.1 h6407bdd_23
    - cctools_osx-arm64 949.0.1 h55de48a_23
    - clang 11.1.0 h694c41f_1
    - clang-11 11.1.0 default_he082bbe_1
    - clang_osx-arm64 11.1.0 h40be2b1_4
    - clangxx 11.1.0 default_he082bbe_1
    - compiler-rt 11.1.0 h654b07c_0
    - compiler-rt_osx-64 11.1.0 h8c5fa43_0
    - ld64_osx-64 530 he8994da_21
    - ld64_osx-arm64 530 h3681fde_21
    - ldid 2.1.2 h6a69015_3
    - libclang-cpp11.1 11.1.0 default_he082bbe_1
    - libcxx 12.0.1 habf9029_0
    - libllvm11 11.1.0 hd011deb_2
    - libllvm12 12.0.1 hd011deb_2
    - libtool 2.4.6 he49afe7_1008
    - libzlib 1.2.11 h9173be1_1013
    - llvm-tools 11.1.0 hd011deb_2
    - make 4.3 h22f3db7_1
    - tapi 1100.0.11 h9ce4665_0
    - zlib 1.2.11 h9173be1_1013
  host:
    - libzlib 1.2.11 hee7b306_1013
    - ncurses 6.2 h9aa5885_4
    - readline 8.1 hedafd6a_0
    - zlib 1.2.11 hee7b306_1013
  run:
    - libzlib >=1.2.11,<1.3.0a0
    - ncurses >=6.2,<6.3.0a0
    - ncurses >=6.2,<6.3.0a0
    - readline >=8.1,<9.0a0
    - readline >=8.1,<9.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - sqlite3 --version
    - test -f $PREFIX/lib/libsqlite3${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libsqlite3.a
    - test -f $PREFIX/include/sqlite3.h
    - test -f $PREFIX/include/sqlite3ext.h
about:
  description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

    public-domain, SQL database engine.It is the most used database engine

    in the world.

    '
  dev_url: https://github.com/mackyle/sqlite
  doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
  doc_url: http://www.sqlite.org/docs.html
  home: http://www.sqlite.org/
  license: Unlicense
  license_url: http://www.sqlite.org/copyright.html
  summary: Implements a self-contained, zero-configuration, SQL database engine
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - snorfalorpagus
