# This file created by conda-build 3.21.7
# ------------------------------------------------

package:
  name: python
  version: 3.9.10
source:
  - md5: e754c4b2276750fd5b4785a1b443683a
    patches:
      - patches/0001-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
      - patches/0002-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
      - patches/0003-Support-cross-compiling-byte-code.patch
      - patches/0004-bpo-45258-search-for-isysroot-in-addition-to-sysroot.patch
      - patches/0005-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
      - patches/0006-Win32-Do-not-download-externals.patch
      - patches/0007-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0008-bpo-22699-Allow-compiling-on-debian-ubuntu-with-a-di.patch
      - patches/0009-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
      - patches/0010-Unvendor-openssl.patch
      - patches/0011-Unvendor-sqlite3.patch
      - patches/0013-Use-ranlib-from-env-if-env-variable-is-set.patch
      - patches/0014-Add-CondaEcosystemModifyDllSearchPath.patch
      - patches/0015-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
      - patches/0016-Doing-d1trimfile.patch
      - patches/0017-cross-compile-darwin.patch
      - patches/0018-Fix-TZPATH-on-windows.patch
      - patches/0019-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
      - patches/0020-Fix-LDSHARED-when-CC-is-overriden-on-Linux-too.patch
      - patches/0021-Unvendor-bzip2.patch
      - patches/0022-Unvendor-libffi.patch
      - patches/0023-Unvendor-tcltk.patch
      - patches/0024-unvendor-xz.patch
      - patches/0025-unvendor-zlib.patch
      - patches/0026-Set-ssltag-to-3.patch
      - patches/0027-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
    url: https://www.python.org/ftp/python/3.9.10/Python-3.9.10.tar.xz
build:
  activate_in_script: true
  detect_binary_files_with_prefix: true
  ignore_run_exports_from:
    - clangxx_osx-arm64 11.*
  no_link: null
  number: 2
  run_exports:
    noarch:
      - python
    weak:
      - python_abi 3.9.* *_cp39
  script_env:
    - CONDA_FORGE=yes
    - PY_INTERP_DEBUG=no
    - PY_INTERP_LINKAGE_NATURE=static
  skip_compile_pyc:
    - '*.py'
  string: hd16f9c5_2_cpython
requirements:
  build:
    - ca-certificates 2021.10.8 h033912b_0
    - cctools_osx-64 973.0.1 h609b070_5
    - cctools_osx-arm64 973.0.1 hd1d4517_5
    - clang 11.1.0 h694c41f_1
    - clang-11 11.1.0 default_he082bbe_1
    - clang_osx-arm64 11.1.0 h7730a26_6
    - clangxx 11.1.0 default_he082bbe_1
    - clangxx_osx-arm64 11.1.0 h862bf99_6
    - compiler-rt 11.1.0 h654b07c_0
    - compiler-rt_osx-64 11.1.0 h8c5fa43_0
    - ld64_osx-64 609 h6adca69_5
    - ld64_osx-arm64 609 h70d1651_5
    - libclang-cpp11.1 11.1.0 default_he082bbe_1
    - libcxx 12.0.1 habf9029_1
    - libiconv 1.16 haf1e3a3_0
    - libllvm11 11.1.0 hd011deb_2
    - libllvm12 12.0.1 hd011deb_2
    - libtool 2.4.6 he49afe7_1008
    - libzlib 1.2.11 h9173be1_1013
    - llvm-tools 11.1.0 hd011deb_2
    - make 4.3 h22f3db7_1
    - openssl 3.0.0 h0d85af4_2
    - pkg-config 0.29.2 h31203cd_1008
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - zlib 1.2.11 h9173be1_1013
  host:
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2021.10.8 h4653dfc_0
    - libffi 3.4.2 h3422bc3_5
    - libzlib 1.2.11 hee7b306_1013
    - ncurses 6.3 hc470f4d_0
    - openssl 1.1.1l h3422bc3_0
    - readline 8.1 hedafd6a_0
    - sqlite 3.37.0 h72a2b83_0
    - tk 8.6.11 he1e0b03_1
    - xz 5.2.5 h642e427_1
    - zlib 1.2.11 hee7b306_1013
  run:
    - bzip2 >=1.0.8,<2.0a0
    - libffi >=3.4.2,<3.5.0a0
    - libzlib >=1.2.11,<1.3.0a0
    - ncurses >=6.3,<7.0a0
    - openssl >=1.1.1l,<1.1.2a
    - readline >=8.1,<9.0a0
    - sqlite >=3.37.0,<4.0a0
    - tk >=8.6.11,<8.7.0a0
    - tzdata
    - xz >=5.2.5,<5.3.0a0
  run_constrained:
    - python_abi 3.9.* *_cp39
test:
  commands:
    - python -V
    - python3 -V
    - 2to3 -h
    - pydoc -h
    - python3-config --help
    - python -c "from zoneinfo import ZoneInfo; from datetime import datetime; dt
      = datetime(2020, 10, 31, 12, tzinfo=ZoneInfo('America/Los_Angeles')); print(dt.tzname())"
    - python -m venv test-venv
    - test-venv/bin/python -c "import ctypes"
    - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
    - for f in ${CONDA_PREFIX}/lib/python*/_sysconfig*.py; do echo "Checking $f:";
      if [[ `rg @ $f` ]]; then echo "FAILED ON $f"; cat $f; exit 1; fi; done
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.a
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.nolto.a
    - pushd tests
    - pushd distutils
    - python setup.py install -v -v
    - python -c "import foobar"
    - popd
    - pushd prefix-replacement
    - bash build-and-test.sh
    - popd
    - pushd cmake
    - cmake -GNinja -DPY_VER=3.9.10
    - popd
    - popd
    - python run_test.py
    - test ! -f default.profraw
  downstreams:
    - cython
    - setuptools
  files:
    - run_test.py
    - tests/cmake/*
    - tests/cython/*
    - tests/distutils/*
    - tests/prefix-replacement/*
  requires:
    - clang_osx-arm64 11.*
    - clangxx_osx-arm64 11.*
    - cmake
    - ninja
    - ripgrep
about:
  description: 'Python is a widely used high-level, general-purpose, interpreted,
    dynamic

    programming language. Its design philosophy emphasizes code

    readability, and its syntax allows programmers to express concepts in

    fewer lines of code than would be possible in languages such as C++ or

    Java. The language provides constructs intended to enable clear programs

    on both a small and large scale.

    '
  dev_url: https://docs.python.org/devguide/
  doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
  doc_url: https://www.python.org/doc/versions/
  home: https://www.python.org/
  license: Python-2.0
  license_file: LICENSE
  summary: General purpose programming language
extra:
  copy_test_source_files: true
  feedstock-name: python
  final: true
  recipe-maintainers:
    - isuruf
    - jakirkham
    - mbargull
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
